## 控制台定义任务配置信息，或通过注解定义任务 (推荐模式)
## Step1. 请先在任务调度控制台创建命名空间和应用分组
spring:
   schedulerx2:
      endpoint: acm.aliyun.com                     #请填写不同region的endpoint
      namespace: aad167f6-8bee-xxxx-xxxx-xxxxxxxxx #region内全局唯一，控制台上创建命名空间时自动生成
      groupId: qianxi.dev                          #应用的id标识，从控制台上创建应用分组时自定义填写，一个命名空间下需要唯一
      appKey: xxxxxxxxxxxxxxxxxxxxxxxx             #应用的key，从控制台上获取
      task:
         scheduling:
            scheduler: schedulerx  # 接管Spring定时任务
# 可选，开启自动同步Spring注解任务
#            sync: true
#            overwrite: false
#      regionId: public
#      aliyunAccessKey: XXXXXXXXX
#      aliyunSecretKey: XXXXXXXXX

logging:
   config: classpath:log4j2.xml